/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rm_desbravador.visao;

import java.text.ParseException;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import rm_desbravador.controler.UIPrincipalControler;
import rm_desbravador.utilitarios.Conexao;
import rm_desbravador.utilitarios.PropertiesLoaderImpl;

/**
 *
 * @author marcos
 */
public class UIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form UIPrincipal
     */
    public UIPrincipal() {
    }

    public void iniciarInterface() {
        initComponents();
        jTFServidor.setText(PropertiesLoaderImpl.getValor("servidor"));
        jTFPorta.setText(PropertiesLoaderImpl.getValor("porta"));
        jTFBanco.setText(PropertiesLoaderImpl.getValor("banco"));
        jTFUsuario.setText(PropertiesLoaderImpl.getValor("usuario"));
        jPFSenha.setText(PropertiesLoaderImpl.getValor("senha"));
        jTFDiretorioCliente.setText(PropertiesLoaderImpl.getValor("dirCliente"));
        try {
            jFTdataCliente.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("##/##/####")));
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        jFTdataCliente.setText(PropertiesLoaderImpl.getValor("dataCliente"));
        jTFDiretorioTitulos.setText(PropertiesLoaderImpl.getValor("dirTitulos"));
        jFTdataTitulos.setText(PropertiesLoaderImpl.getValor("dataTitulos"));
        if ("true".equals(PropertiesLoaderImpl.getValor("tipoBanco"))) {
            jCBBanco.setSelectedIndex(0);
        } else {
            jCBBanco.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFTdataCliente = new javax.swing.JFormattedTextField();
        jTFDiretorioCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBBuscarDirCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAClienteRetorno = new javax.swing.JTextArea();
        jBExportarCliente = new javax.swing.JButton();
        jBFecharCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFTdataTitulos = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFDiretorioTitulos = new javax.swing.JTextField();
        jBBuscarDirTitulo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTATitulosRetorno = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jBFecharTitulo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jBTestarConexao = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTARetornoConfig = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jTFServidor = new javax.swing.JTextField();
        jTFPorta = new javax.swing.JTextField();
        jTFBanco = new javax.swing.JTextField();
        jTFUsuario = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jBFecharConf = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jCBBanco = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(770, 660));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 660));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(756, 712));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(756, 712));

        jLabel1.setText("Data da última exportação: ");

        jFTdataCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel2.setText("Diretório da exportação:");

        jBBuscarDirCliente.setText("Buscar");
        jBBuscarDirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarDirClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Mensangens:");

        jTAClienteRetorno.setColumns(20);
        jTAClienteRetorno.setRows(5);
        jScrollPane1.setViewportView(jTAClienteRetorno);

        jBExportarCliente.setText("Exportar");
        jBExportarCliente.setMaximumSize(new java.awt.Dimension(85, 29));
        jBExportarCliente.setMinimumSize(new java.awt.Dimension(85, 29));
        jBExportarCliente.setPreferredSize(new java.awt.Dimension(85, 29));
        jBExportarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExportarClienteActionPerformed(evt);
            }
        });

        jBFecharCliente.setText("Fechar");
        jBFecharCliente.setMaximumSize(new java.awt.Dimension(97, 29));
        jBFecharCliente.setMinimumSize(new java.awt.Dimension(97, 29));
        jBFecharCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharClienteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jFTdataCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 369, Short.MAX_VALUE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jTFDiretorioCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 413, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBBuscarDirCliente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jBExportarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBFecharCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFTdataCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTFDiretorioCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBBuscarDirCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jBExportarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jBFecharCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(735, 610));

        jLabel4.setText("Data da última exportação: ");

        jFTdataTitulos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel5.setText("Diretório da exportação:");

        jBBuscarDirTitulo.setText("Buscar");
        jBBuscarDirTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarDirTituloActionPerformed(evt);
            }
        });

        jLabel6.setText("Mensangens:");

        jTATitulosRetorno.setColumns(20);
        jTATitulosRetorno.setRows(5);
        jScrollPane2.setViewportView(jTATitulosRetorno);

        jButton4.setText("Exportar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBFecharTitulo.setText("Fechar");
        jBFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharTituloActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jFTdataTitulos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 369, Short.MAX_VALUE))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jTFDiretorioTitulos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 416, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBBuscarDirTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBFecharTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFTdataTitulos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTFDiretorioTitulos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBBuscarDirTitulo))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jBFecharTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(12, 12, 12)))
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Títulos", jPanel3);

        jLabel7.setText("Servidor:");

        jBTestarConexao.setText("Testar conexão");
        jBTestarConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTestarConexaoActionPerformed(evt);
            }
        });

        jLabel9.setText("Mensangens:");

        jTARetornoConfig.setColumns(20);
        jTARetornoConfig.setRows(5);
        jScrollPane3.setViewportView(jTARetornoConfig);

        jLabel10.setText("Porta:");

        jLabel11.setText("Banco:");

        jLabel12.setText("Usuário:");

        jLabel13.setText("Senha:");

        jPFSenha.setText("jPasswordField1");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBFecharConf.setText("Fechar");
        jBFecharConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharConfActionPerformed(evt);
            }
        });

        jLabel14.setText("Conexão:");

        jCBBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SQLServer", "PostGreSQL" }));
        jCBBanco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBBancoItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel11)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel12)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel13))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPFSenha)
                                    .add(jTFServidor)
                                    .add(jTFPorta)
                                    .add(jTFBanco)
                                    .add(jTFUsuario)))
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jBTestarConexao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBSalvar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBFecharConf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                        .add(6, 6, 6))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCBBanco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jCBBanco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTFServidor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTFPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTFBanco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTFUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPFSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jBTestarConexao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jLabel9))
                    .add(jBSalvar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jBFecharConf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 360, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33))
        );

        jTabbedPane1.addTab("Configurações", jPanel5);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 756, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 678, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 770, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 691, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 6, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 7, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBFecharClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharClienteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBFecharClienteActionPerformed

    private void jBBuscarDirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarDirClienteActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione o diretório de destino");
        arquivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        arquivo.showOpenDialog(rootPane);
        jTFDiretorioCliente.setText(arquivo.getSelectedFile().getAbsolutePath());
        PropertiesLoaderImpl.setValor("dirCliente", jTFDiretorioCliente.getText());
    }//GEN-LAST:event_jBBuscarDirClienteActionPerformed

    private void jBFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharTituloActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBFecharTituloActionPerformed

    private void jBBuscarDirTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarDirTituloActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione o diretório de destino");
        arquivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        arquivo.showOpenDialog(rootPane);
        jTFDiretorioTitulos.setText(arquivo.getSelectedFile().getAbsolutePath());
        PropertiesLoaderImpl.setValor("dirTitulos", jTFDiretorioTitulos.getText());
    }//GEN-LAST:event_jBBuscarDirTituloActionPerformed

    private void jBTestarConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTestarConexaoActionPerformed
        Conexao abrirCon = new Conexao();
        boolean tipoBanco;
        if ("true".equals(PropertiesLoaderImpl.getValor("tipoBanco"))) {
            tipoBanco = true;
        } else {
            tipoBanco = false;
        }
        String strPass = new String(jPFSenha.getPassword()).trim();
        abrirCon.getConexao(jTFServidor.getText(), jTFPorta.getText(), jTFBanco.getText(),
                jTFUsuario.getText(), strPass,
                tipoBanco);
        jTARetornoConfig.setText(abrirCon.getMensagemRet() + "\n");
    }//GEN-LAST:event_jBTestarConexaoActionPerformed

    private void jBFecharConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharConfActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBFecharConfActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        String strPass = new String(jPFSenha.getPassword()).trim();
        try {
            PropertiesLoaderImpl.setValor("servidor", jTFServidor.getText());
            PropertiesLoaderImpl.setValor("porta", jTFPorta.getText());
            PropertiesLoaderImpl.setValor("banco", jTFBanco.getText());
            PropertiesLoaderImpl.setValor("usuario", jTFUsuario.getText());
            PropertiesLoaderImpl.setValor("senha", strPass);
            if (jCBBanco.getSelectedIndex() == 0) {
                PropertiesLoaderImpl.setValor("tipoBanco", "true");
            } else {
                PropertiesLoaderImpl.setValor("tipoBanco", "false");
            }
            JOptionPane.showMessageDialog(null, "Configurações salvas", "Informação", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Problema al salvar as configurações\n"
                    + ex, "Informação", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBExportarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExportarClienteActionPerformed
        try {
            UIPrincipalControler uipc = new UIPrincipalControler();
            boolean tipoBanco;
            if ("true".equals(PropertiesLoaderImpl.getValor("tipoBanco"))) {
                tipoBanco = true;
            } else {
                tipoBanco = false;
            }
            Date data = new Date(jFTdataCliente.getText());
            PropertiesLoaderImpl.setValor("dataCliente", jFTdataCliente.getText());
            jTAClienteRetorno.setText(uipc.gerarAquivoClientes(data, jTFDiretorioCliente.getText(),
                    tipoBanco));
            JOptionPane.showMessageDialog(null, "Arquivo exportado\n"
                    + jTFDiretorioCliente.getText() + data.toString() + ".txt",
                    "Informação", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Problema al exportar arquivo\n"
                    + ex, "Informação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBExportarClienteActionPerformed

    private void jCBBancoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBBancoItemStateChanged
        if (jCBBanco.getSelectedIndex() == 0) {
            PropertiesLoaderImpl.setValor("tipoBanco", "true");
        } else {
            PropertiesLoaderImpl.setValor("tipoBanco", "false");
        }
    }//GEN-LAST:event_jCBBancoItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            UIPrincipalControler uipc = new UIPrincipalControler();
            boolean tipoBanco;
            if ("true".equals(PropertiesLoaderImpl.getValor("tipoBanco"))) {
                tipoBanco = true;
            } else {
                tipoBanco = false;
            }
            Date data = new Date(jFTdataTitulos.getText());
            PropertiesLoaderImpl.setValor("dataTitulos", jFTdataTitulos.getText());
            jTATitulosRetorno.setText(uipc.gerarAquivoTitulos(data, jTFDiretorioTitulos.getText(),
                    tipoBanco));
            JOptionPane.showMessageDialog(null, "Arquivo exportado\n"
                    + jTFDiretorioTitulos.getText() + data.toString() + ".txt",
                    "Informação", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Problema al exportar arquivo\n"
                    + ex, "Informação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jBBuscarDirCliente;
    private javax.swing.JButton jBBuscarDirTitulo;
    private javax.swing.JButton jBExportarCliente;
    private javax.swing.JButton jBFecharCliente;
    private javax.swing.JButton jBFecharConf;
    private javax.swing.JButton jBFecharTitulo;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBTestarConexao;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCBBanco;
    private javax.swing.JFormattedTextField jFTdataCliente;
    private javax.swing.JFormattedTextField jFTdataTitulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAClienteRetorno;
    private javax.swing.JTextArea jTARetornoConfig;
    private javax.swing.JTextArea jTATitulosRetorno;
    private javax.swing.JTextField jTFBanco;
    private javax.swing.JTextField jTFDiretorioCliente;
    private javax.swing.JTextField jTFDiretorioTitulos;
    private javax.swing.JTextField jTFPorta;
    private javax.swing.JTextField jTFServidor;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
